---
name: cmpsc-101-fall-2018-lab1
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        labone/CreditCard.java:
            --multi 12 --language Java
            --fragment "println(" --count 6 --exact
# --> check the technical writing
# mdl is a Markdown linting tool
# proselint checks writing for common mistakes
writing/reflection.md:
    mdl
    proselint
    --paragraphs 6 --exact
    --words 100
# --> check the number of commits beyond a threshold
--commits 10
# --> check that the program executes and produces 20 lines of output
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 20 --exact
--command "gradle -q --console plain run" --fragment "Bowman" --count 3 --exact
--command "gradle -q --console plain run" --fragment "272.0" --count 1 --exact
--command "gradle -q --console plain run" --fragment "436.0" --count 1 --exact
